### ISSUE TITLE
Cannot get config variables in checkbox.conf with local run

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#1115]
### Bug Description

When local run, checkbox is not able to get the config variable. This is critical issue because we are not able to test the DUT which can not connect to the network (ethernet, wireless, etc.)
![Screenshot from 2024-03-27 02-06-51](https://github.com/canonical/checkbox/assets/58060146/d6e553b0-39f7-46d4-83cf-43666e96b638)

### To Reproduce

1. Install checkbox
   1. sudo snap install checkbox22 --beta
   2. sudo snap install checkbox --beta --classic
2. List checkbox.conf make sure it is there
   1. sudo checkbox.configure -l
3. Make sure there is an incompleted session
   1. checkbox.checkbox-cli
   2. Select [client-cert-desktop-22-04-stress](https://github.com/canonical/checkbox/blob/11a42fadbae0518c192f375ae526ec2dc13202e0/providers/certification-client/units/client-cert-desktop-22-04.pxu#L161)
   3. Check if boot count for coldboot and warmboot is 100
   4. ctr + c to interrupt
5. Local run checkbox again
   1. checkbox.checkbox-cli
   2. Select [client-cert-desktop-22-04-stress](https://github.com/canonical/checkbox/blob/11a42fadbae0518c192f375ae526ec2dc13202e0/providers/certification-client/units/client-cert-desktop-22-04.pxu#L161)
   3.. You will see that now the boot count is 2 (which is the default value when "$STRESS_BOOT_ITERATIONS" not assigned)

### Environment

 - OS: Desktop 22.04
 - Type: Snap
 - Version: 4.0.0-dev194

### Relevant log output

```shell
ubuntu@kria:~$ sudo checkbox.configure -l
ALSADEVICE=hw:CARD=bytrt5660,DEV=0
MODEL_GRADE=signed
NET_DEVICE_INFO=ven_rsi_sdio ven_rsi_91x
OBEX_TARGET=00:02:72:C5:F9:1F
OPEN_AC_SSID=ubuntu-cert-ac-open
OPEN_AX_SSID=ubuntu-cert-ax-open
OPEN_BG_SSID=ubuntu-cert-bg-open
OPEN_N_SSID=ubuntu-cert-n-open
STRESS_BOOT_ITERATIONS=100  <------------- Here is 100, but in local run is 2 (default)
STRESS_BOOT_WAIT_DELAY=120
STRESS_BOOT_WAKEUP_DELAY=60
STRESS_S3_ITERATIONS=100
STRESS_S3_SLEEP_DELAY=60
STRESS_S3_WAIT_DELAY=120
STRESS_S4_ITERATIONS=100
STRESS_S4_SLEEP_DELAY=60
STRESS_S4_WAIT_DELAY=120
TEST_TARGET_IPERF=10.101.47.93
TPM2TOOLS_DEVICE_FILE=/dev/tpm0
TPM2TOOLS_TCTI_NAME=device
WATCHDOG_KERNEL_MOD=iTCO_wdt
WIFI_AP_SETUPTIME=30
WIFI_INTERFACE=mlan0
WPA_AC_PSK=insecure
WPA_AC_SSID=ubuntu-cert-ac-wpa
WPA_AX_PSK=insecure
WPA_AX_SSID=ubuntu-cert-ax-wpa
WPA_BG_PSK=insecure
WPA_BG_SSID=ubuntu-cert-bg-wpa
WPA_N_PSK=insecure
WPA_N_SSID=ubuntu-cert-n-wpa
WPA3_AX_PSK=insecure
WPA3_AX_SSID=ubuntu-cert-ax-wpa3
WWAN_APN=internet
WWAN_CONTROL_IF=ttyACM3
WWAN_NET_IF=ppp0
WWAN_SETUPTIME=30
```

**Comment by hanhsuan** [comment]
For debian, the config variables could be read correctly by local executing.

**Comment by LiaoU3** [comment]
After deleting all sessions under `/var/tmp/checkbox-ng/sessions/`, this issue did not happen.

**Comment by pieqq** [comment]
I could not reproduce this issue at first, but @Hook25 found the culprit.

To reproduce:

1. Start `checkbox.checkbox-cli`, select the `client-cert-desktop-22-04-stress` test plan

--> there are 100 iterations for warm/cold boot stress tests, as stipulated in `checkbox.checkbox-cli check-config` (OK)

2. Start the testing, and interrupt the session with `Ctrl+C`
3. Start checkbox again. Select the same test plan

--> this time, there are only 2 iterations for the warm/cold boot stress tests.

Why 2? Because this is the [default, hardcoded value in the job](https://github.com/canonical/checkbox/blob/main/providers/base/units/stress/boot.pxu#L31) when the `STRESS_BOOT_ITERATIONS` environment variable is not found:

```
id: reboot-run-generator
category_id: stress-tests
_description:
  Generate a set of IDs corresponding to number of iterations required in the
  reboots tests.
plugin: resource
environ: STRESS_BOOT_ITERATIONS
command:
  ITERATIONS=${STRESS_BOOT_ITERATIONS:-2}
  for i in $(seq 2 "$ITERATIONS"); do
    echo "reboot_id: $i"
    echo "reboot_id_previous: $((i-1))"
    echo
  done
estimated_duration: 1s
flags: preserve-locale
```

**Comment by LiaoU3** [comment]
I can still observed this issue with version `4.0.0-dev196`.
```terminal
ubuntu@kria:~$ snap list
Name                       Version           Rev    Tracking         Publisher             Notes
bare                       1.0               5      latest/stable    canonical✓            base
bugit                      1.2               35     latest/edge      pieq                  devmode
checkbox                   4.0.0-dev196      6401   latest/edge      ce-certification-qa   classic
checkbox22                 4.0.0-dev196      871    latest/edge      ce-certification-qa   -
core20                     20240111          2186   latest/stable    canonical✓            base
core22                     20240111          1125   latest/stable    canonical✓            base
firefox                    124.0.1-1         4039   latest/stable/…  mozilla✓              -
gnome-3-38-2004            0+git.efb213a     145    latest/stable/…  canonical✓            -
gnome-42-2204              0+git.510a601     174    latest/stable/…  canonical✓            -
gtk-common-themes          0.1-81-g442e511   1535   latest/stable/…  canonical✓            -
snap-store                 41.3-77-g7dc86c8  1114   latest/stable/…  canonical✓            -
snapd                      2.61.1            20674  latest/stable/…  canonical✓            snapd
snapd-desktop-integration  0.9               85     latest/stable/…  canonical✓            -
test-snapd-tools-core20    1.0               1      latest/stable    test-snaps-canonical  -
```

**Comment by LiaoU3** [comment]
It seems like this bug has not landed in edge channel yet. I will test it once again tomorrow.

**Comment by LiaoU3** [comment]
@Hook25 This issue can still be observed. The reproduced process you could refer to the [comment](https://github.com/canonical/checkbox/issues/1115#issuecomment-2022304487) from @pieqq

**Comment by pieqq** [comment]
Still haven't found the root cause, but there is clearly something fishy when previous sessions are available in `/var/tmp/checkbox-ng/sessions`.

If there is nothing in `/var/tmp/checkbox-ng/sessions`, local session assistant will run these functions:

1. `select_test_plan` (and `self.config.environment` matches the config file, meaning `STRESS_BOOT_ITERATIONS` is there and set to `100`)
2. `get_bootstrap_todo_list` (ditto)
3. `finish_bootstrap` (ditto)
4. `get_static_todo_list` (ditto)

--> the job selection screen is shown, and I can see 100 iterations for the cold/warm boot jobs (**OK**)

If there is a previous (incomplete) session in `/var/tmp/checkbox-ng/sessions`:

1. `select_test_plan` (and `self.config.environment` matches the config file, meaning `STRESS_BOOT_ITERATIONS` is there and set to `100`)
2. `bootstrap` (ditto)
3. `select_test_plan` **again** (and this time, `self.config.environment` **is empty!**)
4. `get_bootstrap_todo_list` (`self.config.environment` **is empty!**)
5. `finish_bootstrap`  (`self.config.environment` **is empty!**)
6. `get_static_todo_list` (`self.config.environment` **is empty!**)

--> the job selection screen is shown, only 2 iterations for the cold/warm boot jobs (***NOK***)

**Comment by Hook25** [comment]
Please give a look tomorrow (:crossed_fingers: for daily builds) in edge if this is still going on, this was... another issue!

**Comment by LiaoU3** [comment]
After installing checkbox22 and checkbox from edge channel, I found that this issue is fixed.
Now it can get the config varibales correctly after creating another session when there is an incompleted session.

```
checkbox                   4.0.0-dev215                6457   latest/edge      ce-certification-qa  classic
checkbox22                 4.0.0-dev215                880    latest/edge      ce-certification-qa  -
```
![Screenshot from 2024-04-08 10-31-59](https://github.com/canonical/checkbox/assets/58060146/96e51276-2c38-48f3-8f9a-961b388f7f7e)
