### ISSUE TITLE
What's plainbox?

### ISSUE THREAD

**Issue by waveform80** [canonical/checkbox#1278]
### Enhancement Proposal

As someone diving into checkbox for the first time, and attempting to define some new tests, I keep seeing references to "plainbox" (e.g. in the [file format spec](https://checkbox.readthedocs.io/en/stable/reference/units/rfc822.html#plainbox-rfc822-specification)). Unfortunately, nowhere has actually defined *what plainbox is*. After a bit of digging I did discover [the Launchpad page](https://launchpad.net/plainbox) and was pleased to read it has a "well ... documented core". Unfortunately, I haven't manage to find those docs. I did find [the PyPI page](https://pypi.org/project/plainbox/) for the project which has several, unfortunately dead, [documentation links](http://plainbox.readthedocs.org/en/latest/usage.html).

If the answer is basically "it's the core of checkbox" and if plainbox isn't really a separate project at all any more (I see its last release on PyPI was 7 years ago, at the time of writing) perhaps it'd be better to just search'n'replace all those references in the docs and change them to "checkbox"?

I'm happy to file a PR for this, if this is desirable.

**Comment by Hook25** [comment]
Hello, you are right, there is no plainbox anymore, as in: our documentation should not reference it all over the place. 
If you are willing to, feel free to file a pr where you find/replace all occurrences with Checkbox. Do so only in the `docs/` subdirectory, as in the code some plainbox still ramains separate.

As for what plainbox was: it was basically a base on top of which one could build a testing frameword. One such framework is Checkbox (and that we know of, the only one) . Most of this separation is gone nowadays because it caused (and still causes sometimes) quite a few headaches and complications without yielding any benefit.
