### ISSUE TITLE
CPU Frequency Test fails on AMD Genoa and Jammy

### ISSUE THREAD

**Issue by bladernr** [canonical/checkbox#41]
https://certification.canonical.com/hardware/202211-30840/submission/289256/test/110216/result/29829602/

[CpuFreqTest Results]
{0: {400000: ['474%', 'Fail', 1897149], 3709000: ['76%', 'Fail', 2822385]},
 1: {400000: ['474%', 'Fail', 1897149], 3709000: ['76%', 'Fail', 2822403]},
 2: {400000: ['474%', 'Fail', 1897149], 3709000: ['76%', 'Fail', 2822394]},
 3: {400000: ['474%', 'Fail', 1897149], 3709000: ['76%', 'Fail', 2822432]},
 4: {400000: ['474%', 'Fail', 1897149], 3709000: ['76%', 'Fail', 2822428]},
 5: {400000: ['474%', 'Fail', 1897149], 3709000: ['76%', 'Fail', 2822413]},...

**Comment by Hook25** [comment]
Hello, I'm trying to understand what is going on here but it is unclear to me what this issue is about. I was able to recover the link you have provided, it should be accessible now, but I fear I will need more context to fix anything here. @bladernr are you able to remember/provide any? is this affecting you?

**Comment by Hook25** [comment]
I'm doing a cleanup of the backlog, please do re-open this if you see fit
