### ISSUE TITLE
Error "mount: /tmp/tmpppx5la8z: unknown filesystem type 'exfat'." in sd card storage test.

### ISSUE THREAD

**Issue by cvelloth** [canonical/checkbox#448]
### Bug Description

mediacard/sdhc-storage  --- this test is failing during canonical certification suite run on Intel Platform
OS :: Ubuntu 22.04
Kernel : 6.2.7

### To Reproduce

1. Launch checkbox with command checkbox-cli
2. Run the job mediacard/sdhc-storage from the Ubuntu Desktop Preload Certification Test Suite
3. See the error.

### Environment

-OS Ubuntu 22.04
- Snap checkbox version
- Checkbox version (checkbox 2.5 (2373) )
- CPU Intel.

[submission_2023-05-09T06.48.23.748483.zip](https://github.com/canonical/checkbox/files/11428255/submission_2023-05-09T06.48.23.748483.zip)

### Relevant log output

```shell
- Checkbox session(s) (located in `/var/tmp/checkbox-ng/sessions/`, you usually want to select the most recent one)

- logs from the impacted components (e.g. `lsblk` if this is related to an issue when testing a disk...); a safe option is to install and run `sosreport` to gather as much log as possible.

Error Logs ::

mount: /tmp/tmpppx5la8z: unknown filesystem type 'exfat'.
ERROR:root:can't mount /dev/mmcblk0p1
ERROR:root:No device being mounted successfully for testing, aborting
There're total 1 device(s) failed at mounting.
```

**Comment by pieqq** [comment]
Hello @cvelloth and sorry for the long silence.

From the top of my head, we don't support exfat-partitionned drives because, historically, exfat was not officially supported on Linux. This changed a few years ago but we have not looked into that since then.

The usual workaround is to format the pen drive or SD card using fat or ext4. If you have access to a computer with Ubuntu installed on it, you can use the [Disks program to do so.](https://help.gnome.org/users/gnome-help/stable/disk-format.html.en)

**Comment by cvelloth** [comment]
Hi Pierre,

This issue was solved after formatting the SD card. Thank you.
