### ISSUE TITLE
Seperate memory stress to stressor based

### ISSUE THREAD

**Issue by LiaoU3** [canonical/checkbox#487]
### Enhancement Proposal

# Description
Nowadays, we run memory test via a python script like this [line](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/units/memory/jobs.pxu#LL50C17-L50C17). We run all stressor in the same job, so if there's one stressor fail, the memory stress test fail and the rest of the stressor will not be run. It is hard for SWE to debug and also not straight enough to know which stressor cause the failure.

# Questions
1. Is it suitable to break the memory stress into several stressor test?
2. Why do the stressors for [crt](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/bin/stress_ng_test.py#LL225C1-L225C5), [vrt](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/bin/stress_ng_test.py#LL235C12-L235C12) and [ltc](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/bin/stress_ng_test.py#L237) have different runtime parameters for stress-ng command?
3. Why does [ltc](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/bin/stress_ng_test.py#L237) run only 8 thread?

# How
I have a simple idea that maybe we could write a template job for memory stress like these below.
`stress-ng --aggressive --verify --timeout {time} --{stressor} 0`
Then we could run each stressor for one job.

**Comment by pieqq** [comment]
@bladernr Hey! Would you have historical knowledge about stress-ng parameters used when calling it from Checkbox? (see questions above from @LiaoU3 )

**Comment by bladernr** [comment]
> Is it suitable to break the memory stress into several stressor test?

If that's what you want... I think it's a bit of overkill to have another 20 or 30 job definitions just to run single stressors when that is already how the script runs (except for CPU stress which runs them concurrently on purpose).

> We run all stressor in the same job, so if there's one stressor fail, the memory stress test fail and the rest of the stressor will not be run. It is hard for SWE to debug and also not straight enough to know which stressor cause the failure.

As far as we're concerned, if one stressor fails, then yes, the entire thing should fail. We don't want to have "partial success".  Also, Stress-ng dumps a log (or should dump a log) and that should be attached as part of the submission for each run.  There at least is a feature enhancement here to generate named and timestamped logs and attach those to the submission, such as:

jammy-memory-stress-ng-2023-05-31_T12345678-log.gz

But that said, the output does not hide what was run or what failed... at least not that I recall, we just went through several rounds of stress-ng bugs with Colin because of certain stressors failing due to changes in the OS or bugs in stress-ng, all of which were pretty easily found in the output that checkbox captures and displays on C3.

[For example](https://certification.canonical.com/hardware/202212-30947/submission/293783/test/70803/result/30454911/): 

stress-ng: warn:  [3699348] locka: WARNING: bogo-ops counter in non-ready state, metrics are untrustworthy (process may have been terminated prematurely)
stress-ng: info:  [3699279] successful run completed in 240.16s (4 mins, 0.16 secs)
stress-ng: info:  [3699798] setting to a 240 second (4 mins, 0.00 secs) run per stressor
stress-ng: info:  [3699798] dispatching hogs: 256 lockf
stress-ng: info:  [3699798] successful run completed in 240.18s (4 mins, 0.18 secs)
stress-ng: info:  [3700311] setting to a 240 second (4 mins, 0.00 secs) run per stressor
stress-ng: info:  [3700311] dispatching hogs: 256 lockofd
stress-ng: warn:  [3700412] lockofd: WARNING: bogo-ops counter in non-ready state, metrics are untrustworthy (process may have been terminated prematurely)
stress-ng: warn:  [3700501] lockofd: WARNING: bogo-ops counter in non-ready state, metrics are untrustworthy (process may have been terminated prematurely)
stress-ng: warn:  [3700609] lockofd: WARNING: bogo-ops counter in non-ready state, metrics are untrustworthy (process may have been terminated prematurely)
...
07 Dec 16:04: Running stress-ng locka stressor for 240 seconds...
** stress-ng exited with code 7
07 Dec 16:08: Running stress-ng lockf stressor for 240 seconds...
07 Dec 16:12: Running stress-ng lockofd stressor for 240 seconds...
** stress-ng exited with code 7

It's pretty clear that the failure was triggered here by locka and lockfd due to a bogo-ops counter issue (this was a stress-ng bug that we discovered during Jammy cert runs that Colin has since fixed upstream and reflected in our PPAs).  This was a disk test, but the output is consistent for cpu, disk and memory stress runs.

From that you can go back and run locka and lockofd by hand to debug what's happening

There's another feature enhancement there to add the ability to explicitly call a single test case, maybe like:

./stress-ng-test.py --logfile logname single --testcase locka

(that example also incorporates the customized logfile feature mentioned above)

> Why do the stressors for [crt](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/bin/stress_ng_test.py#LL225C1-L225C5), [vrt](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/bin/stress_ng_test.py#LL235C12-L235C12) and [ltc](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/bin/stress_ng_test.py#L237) have different runtime parameters for stress-ng command?

CRT = Constant run time stressors that run for a fixed amount of time.
VRT = Variable run time stressors that run for a time that is calculated based on the amount of RAM
LTC = Low Thread Count stressors that don't work well or trigger false failures if you run too many threads.

These were split out at the suggestion of Colin to thoroughly test things as well as to avoid those false failures.

> Why does [ltc](https://github.com/canonical/checkbox/blob/cc5197a348cc1ad24f25ddc695cef0a70227bd0f/providers/base/bin/stress_ng_test.py#L237) run only 8 thread?

See above. Everything else runs basically 1 thread per core/thread on the CPU, Colin advised to only run those stressors with a limit of 8 or so as that would adequately exercise things and not cause issues with being TOO stressful. e.g. it's the difference between being stressful, and intentionally crashing a test.
